[project]
name = 'Decentralized-Smart-Building-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.building-verification]
path = 'contracts/building-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-optimization]
path = 'contracts/energy-optimization.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-scheduling]
path = 'contracts/maintenance-scheduling.clar'
clarity_version = 2
epoch = 2.5

[contracts.occupancy-tracking]
path = 'contracts/occupancy-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.system-registration]
path = 'contracts/system-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
